AeonInventory/Models/Inventory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AeonInventory.Models
{
    public class Inventory
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string InventoryType { get; set; }
        public string InventoryCode { get; set; }
        public string Configuration { get; set; }
        public string Vendor { get; set; }
        public string PurchaseDate { get; set; }
        public string Location { get; set; }
        public int Quantity { get; set; }
    }
}

AeonInventory/Controllers/InventoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AeonInventory.Models;

namespace AeonInventory.Controllers
{
    public class InventoriesController : Controller
    {
        private DBContext db = new DBContext();

        // GET: Inventories
        
        //public ActionResult Index()
        //{
        //    ViewBag.Locations = new SelectList(db.LocationMasters, "Name", "Name");
        //    return View(db.Inventories.ToList());
        //}
        //[HttpPost]
        public ActionResult Index(string param)
        {
            ViewBag.Locations = new SelectList(db.LocationMasters, "Name", "Name");
            if(param!=null)
            {
                //return View(db.Inventories.Where(x => x.Location == param).ToList());
                if(param!="Select")
                {
                    return PartialView("InventoryDetails", db.Inventories.Where(x => x.Location == param).ToList());
                }
                else
                {
                    return PartialView("InventoryDetails", db.Inventories.ToList());
                }
                
            }
            //return PartialView("InventoryDetails", db.Inventories.ToList());
            return View(db.Inventories.ToList());
        }

        // GET: Inventories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inventory inventory = db.Inventories.Find(id);
            if (inventory == null)
            {
                return HttpNotFound();
            }
            return View(inventory);
        }

        // GET: Inventories/Create
        public ActionResult Create()
        {
            ViewBag.Inventorytype = new SelectList(db.InventoryTypeMasters, "Type", "Type");
            ViewBag.Locations = new SelectList(db.LocationMasters, "Name", "Name");
            return View();
        }

        // POST: Inventories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,Name,InventoryType,InventoryCode,Configuration,Vendor,PurchaseDate,Quantity")] Inventory inventory)
        {
            if (ModelState.IsValid)
            {
                var Location = inventory.InventoryCode;
                var id = 1;
                if (inventory.InventoryType=="Roles")
                {
                    if(db.Inventories.Any(x => x.InventoryType == inventory.InventoryType && x.Location == Location))
                    {
                        Inventory inventories = new Inventory();
                        inventories = db.Inventories.Where(x => x.InventoryType == inventory.InventoryType && x.Location == Location).FirstOrDefault();
                        inventories.Quantity += inventory.Quantity;
                        inventories.PurchaseDate = inventory.PurchaseDate;
                        db.Entry(inventories).State = EntityState.Modified;
                        db.SaveChanges();

                    }                 
                    
                }
                else
                {
                    while (inventory.Quantity > 0)
                    {
                         id = 1;
                        if (db.Inventories.Where(X=>X.Name== inventory.Name).Any())
                        {
                            id = db.Inventories.Max(x => x.id) + 1;
                        }
                        inventory.InventoryCode = Location + "-" + inventory.InventoryType + "-" + id;
                        inventory.Location = Location;
                        db.Inventories.Add(inventory);
                        db.SaveChanges();
                        inventory.Quantity--;
                    }
                }
                

                return RedirectToAction("Index");
            }

            return View(inventory);
        }

        // GET: Inventories/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.Inventorytype = new SelectList(db.InventoryTypeMasters, "Type", "Type");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inventory inventory = db.Inventories.Find(id);
            if (inventory == null)
            {
                return HttpNotFound();
            }
            return View(inventory);
        }

        // POST: Inventories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Name,InventoryType,InventoryCode,Configuration,Vendor,PurchaseDate,Quantity")] Inventory inventory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(inventory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(inventory);
        }

        // GET: Inventories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inventory inventory = db.Inventories.Find(id);
            if (inventory == null)
            {
                return HttpNotFound();
            }
            return View(inventory);
        }

        // POST: Inventories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Inventory inventory = db.Inventories.Find(id);
            db.Inventories.Remove(inventory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AeonInventory/Views/Inventories/Create.cshtml
@model AeonInventory.Models.Inventory

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/_InnerpageLayout.cshtml";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @*@Html.EditorFor(model => model.InventoryCode, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.InventoryCode, new SelectList(@ViewBag.Locations, "Value", "Text"), new { @class = "form-control", id = "ddllocations" })
                @Html.ValidationMessageFor(model => model.InventoryCode, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InventoryType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @*@Html.EditorFor(model => model.InventoryType, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.InventoryType, new SelectList(@ViewBag.Inventorytype, "Value", "Text"), new { @class = "form-control", id = "ddlinventorytype" })
                @Html.ValidationMessageFor(model => model.InventoryType, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            @Html.LabelFor(model => model.Configuration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Configuration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Configuration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vendor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Vendor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vendor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PurchaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.PurchaseDate, new { htmlAttributes = new { @class = "form-control",@type="date" } })
                @Html.ValidationMessageFor(model => model.PurchaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

AeonInventory/Views/Inventories/Delete.cshtml
@model AeonInventory.Models.Inventory

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/_InnerpageLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Inventory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InventoryType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InventoryType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InventoryCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InventoryCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Configuration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Configuration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vendor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vendor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AeonInventory/Views/Inventories/Details.cshtml
@model AeonInventory.Models.Inventory

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/_InnerpageLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Inventory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InventoryType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InventoryType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InventoryCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InventoryCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Configuration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Configuration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vendor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vendor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AeonInventory/Views/Inventories/Edit.cshtml
@model AeonInventory.Models.Inventory

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/_InnerpageLayout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Inventory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InventoryType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @*@Html.EditorFor(model => model.InventoryType, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.InventoryType, new SelectList(@ViewBag.Inventorytype, "Value", "Text"), new { @class = "form-control", id = "ddlinventorytype" })
                @Html.ValidationMessageFor(model => model.InventoryType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InventoryCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.InventoryCode, new { htmlAttributes = new { @class = "form-control" } })
                
                @Html.ValidationMessageFor(model => model.InventoryCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Configuration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Configuration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Configuration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vendor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Vendor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vendor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PurchaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.PurchaseDate, new { htmlAttributes = new { @class = "form-control",@type="date" } })
                @Html.ValidationMessageFor(model => model.PurchaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

AeonInventory/Views/Inventories/Index.cshtml
@model IEnumerable<AeonInventory.Models.Inventory>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_InnerpageLayout.cshtml";
}


<style media="Print" type="text/css">
    .ctrl {
        display: none;
    }
</style>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>



<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="col-md-2" style="float:right;">
    <input type="button" id="btnprint" name="btnshow" onclick="printdiv('divInventories');" value="Print" class="btn btn-success" />
</div>
<div class="form-group">
    @*@Html.LabelFor(model => model.InventoryCode, htmlAttributes: new { @class = "control-label col-md-2" })*@
    <div class="col-md-4">
        @*@Html.EditorFor(model => model.InventoryCode, new { htmlAttributes = new { @class = "form-control" } })*@
        @Html.DropDownList("ddllocations", new SelectList(@ViewBag.Locations, "Value", "Text"), new { @class = "form-control", id = "ddllocations" })
    </div>
</div>
<div id="divInventories">
    
   @{ Html.RenderPartial("InventoryDetails");  }
</div>
@section Scripts {
<script src="~/Scripts/JavaScript.js"></script>
    <script>
        $("#ddllocations").on("change",(function () {
        var model = {param: $(this).val() };
            $.ajax({
                url: "@(Url.Action("Index", "Inventories"))",
                type: "GET",
                //dataType: "JSON",
                data: { "param": $(this).val() },
                success: function (data) {
                    $('#divInventories').html(" ");
                    $('#divInventories').html(data);
            console.log(data);

        },
                error: function (jqXHR, textStatus, errorThrown) {
                    //console.log(data);
                    /*debugger*/;
        alert(textStatus, errorThrown, jqXHR);
                }
            });
        }));
    </script>
    }

    

AeonInventory/Views/Inventories/InventoryDetails.cshtml
@model IEnumerable<AeonInventory.Models.Inventory>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InventoryType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InventoryCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Configuration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vendor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PurchaseDate)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InventoryType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InventoryCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Configuration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vendor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PurchaseDate)
            </td>

            <td class="ctrl actions">
                @Html.ActionLink("Edit", "Edit", new { id = item.id, @class = "ctrl" }) |
                @Html.ActionLink("Details", "Details", new { id = item.id, @class = "ctrl" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id, @class = "ctrl" })
            </td>
        </tr>
    }

</table>